window.VANAR_COPY = {
  es: {
    nav: {
      what: "Qué hacemos",
      services: "Servicios",
      product: "Predictable.ai",
      proof: "Validación",
      contact: "Contacto",
      cta: "Agendar sesión",
    },
    hero: {
      eyebrow: "Vanar · Soluciones Integrales Corporativas",
      title_1: "La",
      title_2: "infraestructura",
      title_3: "corporativa que ejecuta —no recomienda.",
      sub: "Diseñamos, implementamos y operamos sistemas integrales en las áreas críticas de su empresa: comercial, finanzas, tecnología, logística, seguros y salud ocupacional. Donde las consultoras entregan análisis, nosotros entregamos operación.",
      cta_primary: "Agendar sesión de diagnóstico",
      cta_secondary: "Conocer Predictable.ai 🚀",
      meta_a: "Activo en 10 países",
      meta_b: "3 continentes",
      meta_c: "+50 empresas",
    },
    pillars: {
      eyebrow: "Seis pilares operativos",
      title: "Seis verticales. Un mismo principio: instalar y operar.",
      sub: "No somos una consultora. Somos la firma que implementa la arquitectura corporativa —y la opera hasta que funciona.",
      items: [
        { code: "P.01", t: "Ejecución Comercial", d: "Revenue architecture, hunting, qualification, closing discipline, retention y expansion. Pipeline operable con forecast confiable.", kpi: "Predictibilidad de revenue", featured: true },
        { code: "P.02", t: "Finanzas Corporativas", d: "Arquitectura financiera, control, reporting, governance, planeación y gestión de tesorería para empresas en crecimiento.", kpi: "Control financiero" },
        { code: "P.03", t: "Tecnología", d: "Integraciones, arquitectura de datos, automatización de procesos, seguridad operativa y modernización de sistemas core.", kpi: "Stack operable" },
        { code: "P.04", t: "Logística", d: "Diseño de operación, cadena de suministro, distribución, gestión de inventarios y SLAs. Procesos que sostienen el crecimiento.", kpi: "Continuidad operativa" },
        { code: "P.05", t: "Seguros Corporativos", d: "Cobertura de riesgos críticos, programas ejecutivos, pólizas estratégicas y estructuración de carteras corporativas.", kpi: "Riesgo gobernado" },
        { code: "P.06", t: "Salud Ocupacional", d: "Cumplimiento normativo, bienestar, programas de prevención y continuidad del talento. Operación humana sana.", kpi: "Cumplimiento 100%" },
      ],
    },
    stats: {
      title: "Por qué existen las soluciones integrales",
      subtitle: "Las empresas no fallan por falta de ideas. Fallan por falta de sistemas que ejecuten las ideas. Esta es la realidad:",
      items: [
        { k: "69%", l: "de vendedores B2B no cumplió cuota en 2024", src: "Ebsta B2B Benchmark" },
        { k: "~12%", l: "cumple proyecciones de forma consistente", src: "Dato de campo · Vanar" },
        { k: "408", l: "días de ciclo de venta promedio mid-market", src: "Sword & the Script 2024" },
        { k: "55%", l: "de líderes no confía en su forecast", src: "Gartner 2024" },
      ],
    },
    problem: {
      eyebrow: "El problema",
      title: "Dirección con intuición. Operación en silos. Resultados impredecibles.",
      lead: "",
      symptoms: [
        { t: "Áreas desconectadas", d: "Cada vertical con su propia verdad." },
        { t: "Consultoras sin ejecución", d: "Reportes que viven en el cajón." },
        { t: "Dependencia del comercial estrella", d: "Si se va, el sistema colapsa." },
        { t: "Tecnología sin lógica de negocio", d: "Herramientas caras que nadie usa bien." },
      ],
    },
    how: {
      eyebrow: "Cómo operamos",
      title: "Tres capas integradas. Seis verticales. Un solo sistema.",
      sub: "Vanar no entrega PowerPoints. Instala y opera la arquitectura que las áreas críticas necesitan para funcionar juntas y cumplir el plan.",
      layers: [
        { n: "01", t: "Diseño", d: "Arquitectura por vertical y transversal: ICP, procesos, controles, métricas, gobernanza, modelo de capacidad, playbooks y responsabilidades por rol.", tags: ["Arquitectura", "Governance", "Procesos", "Capacity"] },
        { n: "02", t: "Implementación", d: "Lo llevamos al terreno: tecnología, CRM, ERP, workflows, dashboards, cadencias, alertas, rutinas de reporting y estructura operativa real.", tags: ["Implementación", "Tech", "Playbooks", "Dashboards"] },
        { n: "03", t: "Operación", d: "Ejecutamos en campo, monitoreamos, detectamos cuellos de botella, corregimos desvíos y protegemos el cumplimiento trimestre tras trimestre.", tags: ["Operación", "Revenue Assurance", "Correcciones", "Mejora continua"] },
      ],
    },
    diff: {
      eyebrow: "Por qué Vanar",
      title: "Lo que otros hacen. Lo que nosotros instalamos.",
      rows: [
        { a: "Consultoras tradicionales", b: "Entregan análisis, recomendaciones y planes estratégicos.", c: "Instalamos la operación y la corremos. Nos pagan por el resultado, no por el reporte." },
        { a: "Agencias especializadas", b: "Resuelven un área (leads, ads, HR, IT).", c: "Arquitectura integral que conecta las áreas críticas en un solo sistema operable." },
        { a: "Software genérico (CRM/ERP)", b: "Organiza información y tareas.", c: "Diseñamos la lógica de negocio que el software por sí solo no puede inventar." },
        { a: "In-house fragmentado", b: "Cada área con su stack, su proceso y su verdad.", c: "Un layer transversal que gobierna, mide y coordina las seis verticales." },
      ],
    },
    product: {
      eyebrow: "Producto · Predictable.ai",
      title: "Nuestra capa tecnológica para la vertical comercial.",
      tagline: "The operating system for predictable revenue.",
      desc: "Predictable.ai es la startup tecnológica de Vanar. Convierte nuestra metodología de ejecución comercial en una plataforma: visibilidad de pipeline, modelado de capacidad, monitoreo de cumplimiento y activación de intervención en tiempo real.",
      relationship_a: "Vanar",
      relationship_a_d: "Infraestructura corporativa integral. Seis verticales operadas en campo. Metodología validada con clientes en 10 países.",
      relationship_b: "Predictable.ai",
      relationship_b_d: "Capa de software que instrumenta la vertical comercial. Visibilidad, monitoreo de cumplimiento y activación de intervención.",
      modules: ["Pipeline Intelligence", "Hunting OS", "Qualification Engine", "Revenue Capacity Planner", "Tender OS", "Retention & Expansion Signals", "Revenue Risk Dashboard"],
      cta: "Ir a Predictable.ai",
      cta_sub: "predictableai.vanarsi.com",
    },
    proof: {
      eyebrow: "Validación de campo",
      title: "No teorizamos. Operamos.",
      sub: "Eleva —co-fundada por el equipo fundador de Vanar— es una prueba de concepto viva de la metodología en la vertical comercial. Hoy opera en 5 países, 3 continentes y 3 sectores estratégicos.",
      items: [
        { k: "42", l: "meetings/mes generados con un solo cliente" },
        { k: "5+", l: "países operando actualmente" },
        { k: "3", l: "continentes con clientes activos" },
        { k: "3", l: "sectores: finanzas, tech, textiles" },
      ],
      quote: "No promete esfuerzo corporativo. Construye capacidad corporativa.",
      quote_by: "— Principio operativo de Vanar",
    },
    contact: {
      eyebrow: "Siguiente paso",
      title: "Conozca cómo Vanar puede operar las áreas críticas de su empresa.",
      sub: "Una sesión de <30 minutos donde revisamos arquitectura actual por vertical, fugas operativas y palancas específicas de ROI para su compañía.",
      cta: "Agendar sesión",
      alt: "Escríbenos",
      email: "aaron@vanarsi.com",
    },
    footer: {
      strap: "Soluciones integrales corporativas. Infraestructura que ejecuta —no recomienda.",
      cols: { company: "Compañía", product: "Producto", resources: "Recursos", legal: "Legal" },
    },
  },
  en: {
    nav: {
      what: "What we do",
      services: "Services",
      product: "Predictable.ai",
      proof: "Proof",
      contact: "Contact",
      cta: "Book a session",
    },
    hero: {
      eyebrow: "Vanar · Integrated Corporate Solutions",
      title_1: "The corporate",
      title_2: "infrastructure",
      title_3: "that executes —not recommends.",
      sub: "We design, implement and operate integrated systems across your company's critical verticals: commercial, finance, technology, logistics, insurance and occupational health. Where consultancies deliver reports, we deliver operation.",
      cta_primary: "Book a diagnostic session",
      cta_secondary: "See Predictable.ai",
      meta_a: "Active in 10 countries",
      meta_b: "3 continents",
      meta_c: "+50 companies",
    },
    pillars: {
      eyebrow: "Six operating pillars",
      title: "Six verticals. One principle: install and operate.",
      sub: "We're not a consultancy. We're the firm that implements the corporate architecture —and runs it until it works.",
      items: [
        { code: "P.01", t: "Commercial Execution", d: "Revenue architecture, hunting, qualification, closing discipline, retention and expansion. An operable pipeline with a trustworthy forecast.", kpi: "Revenue predictability", featured: true },
        { code: "P.02", t: "Corporate Finance", d: "Financial architecture, control, reporting, governance, planning and treasury management for growing companies.", kpi: "Financial control" },
        { code: "P.03", t: "Technology", d: "Integrations, data architecture, process automation, operational security and modernization of core systems.", kpi: "Operable stack" },
        { code: "P.04", t: "Logistics", d: "Operations design, supply chain, distribution, inventory management and SLAs. Processes that sustain growth.", kpi: "Operational continuity" },
        { code: "P.05", t: "Corporate Insurance", d: "Critical risk coverage, executive programs, strategic policies and structuring of corporate portfolios.", kpi: "Governed risk" },
        { code: "P.06", t: "Occupational Health", d: "Regulatory compliance, wellbeing, prevention programs and talent continuity. Healthy human operation.", kpi: "100% compliance" },
      ],
    },
    stats: {
      title: "Why integrated solutions exist",
      subtitle: "Companies don't fail for lack of ideas. They fail for lack of systems that execute them. Here's the reality:",
      items: [
        { k: "69%", l: "of B2B sellers missed quota in 2024", src: "Ebsta B2B Benchmark" },
        { k: "~12%", l: "consistently hit their projections", src: "Field data · Vanar" },
        { k: "408", l: "average mid-market sales cycle (days)", src: "Sword & the Script 2024" },
        { k: "55%", l: "of leaders don't trust their forecast", src: "Gartner 2024" },
      ],
    },
    problem: {
      eyebrow: "The problem",
      title: "Leadership on intuition. Operation in silos. Unpredictable results.",
      lead: "",
      symptoms: [
        { t: "Disconnected areas", d: "Every vertical with its own truth." },
        { t: "Consultancies without execution", d: "Reports that live in the drawer." },
        { t: "Star-rep dependency", d: "If they leave, the system collapses." },
        { t: "Tech without business logic", d: "Expensive tools nobody uses well." },
      ],
    },
    how: {
      eyebrow: "How we operate",
      title: "Three integrated layers. Six verticals. One single system.",
      sub: "Vanar doesn't hand over PowerPoints. We install and run the architecture that critical areas need to work together and meet the plan.",
      layers: [
        { n: "01", t: "Design", d: "Per-vertical and cross-cutting architecture: ICP, processes, controls, metrics, governance, capacity model, playbooks and role ownership.", tags: ["Architecture", "Governance", "Processes", "Capacity"] },
        { n: "02", t: "Implementation", d: "We bring it to the field: technology, CRM, ERP, workflows, dashboards, cadences, alerts, reporting routines and real operational structure.", tags: ["Implementation", "Tech", "Playbooks", "Dashboards"] },
        { n: "03", t: "Operation", d: "We execute in the field, monitor, detect bottlenecks, correct deviations and protect attainment quarter after quarter.", tags: ["Operation", "Revenue Assurance", "Corrections", "Continuous improvement"] },
      ],
    },
    diff: {
      eyebrow: "Why Vanar",
      title: "What others do. What we install.",
      rows: [
        { a: "Traditional consultancies", b: "Deliver analysis, recommendations and strategic plans.", c: "We install the operation and run it. We're paid for results, not the report." },
        { a: "Specialized agencies", b: "Solve one area (leads, ads, HR, IT).", c: "Integrated architecture connecting critical areas in a single operable system." },
        { a: "Generic software (CRM/ERP)", b: "Organizes information and tasks.", c: "We design the business logic software alone cannot invent." },
        { a: "Fragmented in-house", b: "Every area with its stack, its process and its truth.", c: "A cross-cutting layer that governs, measures and coordinates the six verticals." },
      ],
    },
    product: {
      eyebrow: "Product · Predictable.ai",
      title: "Our technology layer for the commercial vertical.",
      tagline: "The operating system for predictable revenue.",
      desc: "Predictable.ai is Vanar's technology startup. It turns our commercial execution methodology into a platform: pipeline visibility, capacity modeling, attainment monitoring and real-time intervention activation.",
      relationship_a: "Vanar",
      relationship_a_d: "Integrated corporate infrastructure. Six verticals operated in the field. Methodology validated with clients in 10 countries.",
      relationship_b: "Predictable.ai",
      relationship_b_d: "Software layer instrumenting the commercial vertical. Visibility, attainment monitoring and intervention activation.",
      modules: ["Pipeline Intelligence", "Hunting OS", "Qualification Engine", "Revenue Capacity Planner", "Tender OS", "Retention & Expansion Signals", "Revenue Risk Dashboard"],
      cta: "Go to Predictable.ai",
      cta_sub: "predictableai.vanarsi.com",
    },
    proof: {
      eyebrow: "Field validation",
      title: "We don't theorize. We operate.",
      sub: "Eleva —co-founded by Vanar's founding team— is a living proof of concept for the methodology in the commercial vertical. Today it operates across 5 countries, 3 continents and 3 strategic sectors.",
      items: [
        { k: "42", l: "meetings/month with a single client" },
        { k: "5+", l: "countries currently operating" },
        { k: "3", l: "continents with active clients" },
        { k: "3", l: "sectors: finance, tech, textiles" },
      ],
      quote: "We don't promise corporate effort. We build corporate capacity.",
      quote_by: "— Vanar operating principle",
    },
    contact: {
      eyebrow: "Next step",
      title: "See how Vanar can operate your company's critical areas.",
      sub: "A 60-minute diagnostic session reviewing current architecture per vertical, operational leaks and specific ROI levers for your company.",
      cta: "Book a session",
      alt: "Write to us",
      email: "contact@vanarsi.com",
    },
    footer: {
      strap: "Integrated corporate solutions. Infrastructure that executes —not recommends.",
      cols: { company: "Company", product: "Product", resources: "Resources", legal: "Legal" },
    },
  },
};
