window.VANAR_EXTRA = {
  es: {
    clients: {
      title: "Operamos con empresas en 10 países",
      sub: "Finanzas, tech, seguros, logística, textiles. Compañías que dejaron de improvisar y pasaron a operar.",
    },
    pain: {
      eyebrow: "Pain → Solución",
      title: "Cinco dolores que escuchamos cada semana.",
      sub: "Mueva el control para ver el antes (lo que hoy vive en su empresa) y el después (lo que Vanar instala).",
      items: [
        { pain: "No sé qué va a cerrar el trimestre", solution: "Forecast con probabilidad por oportunidad. Coverage ratio en tiempo real. Dashboard de attainment con 94% de precisión vs. cierre real.", metric: "94%", metric_l: "precisión de forecast" },
        { pain: "Dependo del comercial estrella", solution: "Playbooks, cadencias y qualification frameworks instalados. Sistema ejecutable por cualquier miembro del equipo. Onboarding de 30 días, no 6 meses.", metric: "30d", metric_l: "ramp-up por rep" },
        { pain: "Pago consultoras que solo recomiendan", solution: "Vanar cobra por operación ejecutada, no por PPT entregado. Usted paga cuando el sistema corre.", metric: "0%", metml: "", metric_l: "reportes archivados" },
        { pain: "Mi CRM es un basurero", solution: "Arquitectura de datos limpia. Lógica de negocio instalada sobre HubSpot/Salesforce. Gobernanza activa. El CRM se vuelve fuente de verdad operable.", metric: "1x", metric_l: "fuente de verdad" },
        { pain: "Mis áreas no hablan entre sí", solution: "Capa transversal que conecta comercial, finanzas y operaciones. Un dashboard directivo. Un lenguaje. Un sistema.", metric: "6", metric_l: "verticales coordinadas" },
      ],
    },
    roi: {
      eyebrow: "ROI calculator",
      title: "Ajuste los números de su empresa.",
      sub: "Cuatro palancas que Vanar opera diferente. Mueva los controles y compare su operación actual con la metodología Vanar.",
      channels_l: "Canales de prospección activos",
      channels_h: "Email · LinkedIn · WhatsApp · Llamada · Referidos · Eventos · ABM",
      employees_l: "Headcount del equipo comercial",
      employees_h: "Costo operacional crece lineal con headcount",
      conv_l: "Tasa de conversión promedio",
      conv_h: "Email <1% · Otros canales 1-3% · Vanar 5-10%",
      meetings_l: "Reuniones calificadas al mes",
      meetings_h: "Vanar apunta a calidad: 7-15 reuniones con 30-50% conversión",
      out_title: "Resultado · operación Vanar",
      out_pipeline: "Pipeline calificado",
      out_cost: "Costo operacional",
      out_conv: "Conversión esperada",
      out_roi: "ROI multiplicador",
      vanar_preset: "Aplicar metodología Vanar",
      your_preset: "Su situación actual",
      disclaimer: "Basado en data de campo Vanar + benchmarks Ebsta 2024. El diagnóstico ajusta el modelo a su industria.",
    },
  },
  en: {
    clients: {
      title: "We operate with companies across 10 countries",
      sub: "Finance, tech, insurance, logistics, textiles. Companies that stopped improvising and started operating.",
    },
    pain: {
      eyebrow: "Pain → Solution",
      title: "Five pains we hear every single week.",
      sub: "Move the handle to see before (what lives in your company today) and after (what Vanar installs).",
      items: [
        { pain: "I don't know what will close this quarter", solution: "Forecast with probability per opportunity. Real-time coverage ratio. Attainment dashboard with 94% precision vs. actual close.", metric: "94%", metric_l: "forecast precision" },
        { pain: "I depend on the star rep", solution: "Playbooks, cadences and qualification frameworks installed. System executable by any team member. 30-day onboarding, not 6 months.", metric: "30d", metric_l: "ramp per rep" },
        { pain: "I pay consultants that only recommend", solution: "Vanar charges for executed operation, not slides delivered. You pay when the system runs.", metric: "0%", metric_l: "reports archived" },
        { pain: "My CRM is a dumpster", solution: "Clean data architecture. Business logic installed on top of HubSpot/Salesforce. Active governance. CRM becomes the operable source of truth.", metric: "1×", metric_l: "single source" },
        { pain: "My areas don't talk to each other", solution: "Cross-cutting layer connecting commercial, finance and operations. One executive dashboard. One language. One system.", metric: "6", metric_l: "verticals coordinated" },
      ],
    },
    roi: {
      eyebrow: "ROI calculator",
      title: "Adjust your company's numbers.",
      sub: "Four levers Vanar operates differently. Move the controls and compare your current operation to the Vanar methodology.",
      channels_l: "Active prospecting channels",
      channels_h: "Email · LinkedIn · WhatsApp · Call · Referrals · Events · ABM",
      employees_l: "Commercial team headcount",
      employees_h: "Operational cost grows linearly with headcount",
      conv_l: "Average conversion rate",
      conv_h: "Email <1% · Other channels 1-3% · Vanar 5-10%",
      meetings_l: "Qualified meetings per month",
      meetings_h: "Vanar targets quality: 7-15 meetings at 30-50% conversion",
      out_title: "Result · Vanar operation",
      out_pipeline: "Qualified pipeline",
      out_cost: "Operational cost",
      out_conv: "Expected conversion",
      out_roi: "ROI multiplier",
      vanar_preset: "Apply Vanar methodology",
      your_preset: "Your current setup",
      disclaimer: "Based on Vanar field data + Ebsta 2024 benchmarks. Diagnostic adjusts the model to your industry.",
    },
  },
};

window.VANAR_CLIENTS = [
  { m: "Bm", n: "Botmaker" },
  { m: "Tl", n: "Talently" },
  { m: "BCP", n: "BCP" },
  { m: "Sms", n: "Siemens" },
  { m: "Ic", n: "Intercorp" },
  { m: "Mn", n: "Monnet" },
  { m: "Bx", n: "Banyax" },
  { m: "Lg", n: "Legalario" },
  { m: "TdM", n: "Tec de Monterrey" },
  { m: "Ltm", n: "LATAM Airlines" },
  { m: "Ut", n: "UTEC" },
  { m: "Cp", n: "Cinépolis" },
  { m: "Sd", n: "Santander" },
  { m: "b2b", n: "bit2bit Americas" },
  { m: "STP", n: "STP Ventures" },
];
